### ISSUE TITLE
Invalid parameter values during training

### ISSUE THREAD

**Issue by katimbach** [JinmiaoChenLab/scTM#6]
I am trying to run the pipeline on a single sample. I installed the necessary PyTorch with compatibility of the CUDA module I have available (11.7) to run the training with GPU. I am reading in raw counts (from Xenium 5K data), I preprocess the data, define 50 neighbors for constructing the graph, and run it for 30 topics, as:
```
import os
import sys

import torch

# Check if CUDA is available
if torch.cuda.is_available():
    print("CUDA is available.")
    print("Using device:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available. Using CPU.")

import anndata as ad
import numpy as np
import pandas as pd
import scanpy as sc
import scipy
import seaborn as sns
import sctm
import squidpy as sq

#%load_ext autoreload
#%autoreload 2

path = "/mnt/beegfs/kimbach/OV_proj/AnnData/Xenium/"
sample = sys.argv[1]
#sample = "STR618"

print(f"Processing data for: {sample}")

adata = sc.read_hdf(path + sample + "_input.h5", key= "counts")
image = pd.read_csv(path + sample + "_coords.csv", index_col=0)
cells = pd.read_csv(path + sample + "_cells.tsv", sep='\t')
genes = pd.read_csv(path + sample + "_genes.tsv", sep='\t')
meta = pd.read_csv(path + sample + "_meta.tsv", sep='\t')

adata.var_names = genes.x
adata.obs_names = cells.x
adata.obsm["spatial"]=image[["x", "y"]].to_numpy()
adata.obs["sample"]=sample

adata.obs["ct"] = meta["cell_type_specific"].tolist()
adata.obs["ct"] = adata.obs["ct"].astype("category")

adata.var_names_make_unique()

sc.pp.calculate_qc_metrics(adata, inplace=True)
adata.layers["counts"] = adata.X.copy()

sctm.pp.filter_genes(adata, 0.01)

sq.gr.spatial_neighbors(adata, n_neighs=50)

sctm.seed.seed_everything(0)

n_topics = 30

model = sctm.stamp.STAMP(
    adata,
    n_topics = n_topics,
    layer="counts",
    gene_likelihood="nb")

model.train(learning_rate = 0.01)
```

However, after completing 10% of the training epochs, it fails with the following error:
```
  0%|          | 0/800 [00:00<?, ?it/s]/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/primitives.py:478: UserWarning: encod
er.norm_topic.0.weight was not registered in the param store because requires_grad=False. You can silence this warning by calling my_module.train(False)
  warnings.warn(
Epoch Loss:644.815:   0%|          | 4/800 [00:52<2:12:56, 10.02s/it]
Epoch Loss:643.647:   1%|          | 8/800 [01:29<2:06:05,  9.55s/it]
Epoch Loss:643.097:   2%|▏         | 12/800 [02:07<2:04:22,  9.47s/it]
Epoch Loss:642.687:   2%|▏         | 17/800 [02:45<2:04:14,  9.51s/it]
Epoch Loss:642.475:   3%|▎         | 21/800 [03:23<2:03:07,  9.48s/it]
Epoch Loss:642.219:   3%|▎         | 25/800 [04:01<2:03:07,  9.53s/it]
Epoch Loss:642.200:   4%|▎         | 29/800 [04:39<2:02:19,  9.52s/it]
Epoch Loss:642.057:   4%|▍         | 33/800 [05:17<2:01:19,  9.49s/it]
Epoch Loss:641.991:   5%|▍         | 37/800 [06:04<2:00:22,  9.47s/it]
Epoch Loss:641.946:   5%|▌         | 41/800 [06:42<1:59:56,  9.48s/it]
Epoch Loss:641.798:   6%|▌         | 45/800 [07:20<1:59:06,  9.47s/it]
Epoch Loss:641.782:   6%|▋         | 49/800 [07:58<1:58:24,  9.46s/it]
Epoch Loss:635.528:   7%|▋         | 54/800 [08:37<2:00:17,  9.66s/it]
Epoch Loss:635.875:   7%|▋         | 58/800 [09:18<2:04:51, 10.10s/it]
Epoch Loss:635.469:   8%|▊         | 62/800 [09:58<2:04:46, 10.14s/it]
Epoch Loss:635.585:   8%|▊         | 66/800 [10:39<2:04:07, 10.15s/it]
Epoch Loss:635.549:   9%|▉         | 70/800 [11:20<2:03:58, 10.19s/it]
Epoch Loss:635.327:   9%|▉         | 74/800 [12:10<2:03:15, 10.19s/it]
Epoch Loss:634.896:  10%|▉         | 78/800 [12:44<1:57:52,  9.80s/it]
Traceback (most recent call last):
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 191, in __call__
    ret = self.fn(*args, **kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 32, in _context_wrap
    return fn(*args, **kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/sctm/model.py", line 688, in guide
    pyro.sample("disp", dist.LogNormal(self.disp_loc, self.disp_scale))
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py", line 26, in __call__
    return super().__call__(*args, **kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/distributions/torch.py", line 207, in __init__
    base_dist = Normal(loc, scale)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py", line 26, in __call__
    return super().__call__(*args, **kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/torch/distributions/distribution.py", line 62, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Parameter of shape (3145,)) of distribution Normal(loc: torch.Size([3145]), scale: torch.Size([3145])) to satisfy 
the constraint Real(), but found invalid values:
Parameter containing:
tensor([-1.0711,  0.2974,  0.1966,  ..., -0.4964, -0.6241, -0.8947],
       device='cuda:0', requires_grad=True)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "OV_xenium_stamp_sample.py", line 72, in <module>
    model.train(learning_rate = 0.01)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/sctm/stamp.py", line 380, in train
    batch_loss = svi.step(
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/infer/svi.py", line 145, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_elbo.py", line 140, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/infer/elbo.py", line 237, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_mean_field_elbo.py", line 82, in _get_trace
    model_trace, guide_trace = super()._get_trace(model, guide, args, kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_elbo.py", line 57, in _get_trace
    model_trace, guide_trace = get_importance_trace(
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/infer/enum.py", line 60, in get_importance_trace
    guide_trace = poutine.trace(guide, graph_type=graph_type).get_trace(
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 216, in get_trace
    self(*args, **kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 198, in __call__
    raise exc from e
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 191, in __call__
    ret = self.fn(*args, **kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 32, in _context_wrap
    return fn(*args, **kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/sctm/model.py", line 688, in guide
    pyro.sample("disp", dist.LogNormal(self.disp_loc, self.disp_scale))
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py", line 26, in __call__
    return super().__call__(*args, **kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/distributions/torch.py", line 207, in __init__
    base_dist = Normal(loc, scale)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py", line 26, in __call__
    return super().__call__(*args, **kwargs)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/mnt/beegfs/kimbach/bin/.conda/envs/sctm/lib/python3.8/site-packages/torch/distributions/distribution.py", line 62, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Parameter of shape (3145,)) of distribution Normal(loc: torch.Size([3145]), scale: torch.Size([3145])) to satisfy 
the constraint Real(), but found invalid values:
Parameter containing:
tensor([-1.0711,  0.2974,  0.1966,  ..., -0.4964, -0.6241, -0.8947],
       device='cuda:0', requires_grad=True)
    Trace Shapes:          
     Param Sites:          
    Sample Sites:          
      sample dist         |
            value     256 |
        caux dist       1 |
            value       1 |
       delta dist    3145 |
            value    3145 |
          bg dist    3145 |
            value    3145 |
         tau dist 30    1 |
            value 30    1 |
     lambda_ dist 30 3145 |
            value 30 3145 |
        beta dist 30 3145 |
            value 30 3145 |
z_topic_diag dist       1 |
            value       1 |
  z_topic_lr dist 30   30 |
            value 30   30 |
```
Any idea why this might be happening or how to resolve it?

**Comment by katimbach** [comment]
I was able to resolve this by adjusting the learning rate, which at default was too high for my run. Decreasing to 0.001 resulted in similar run time and epoch loss values.

**Comment by Chengwei94** [comment]
@katimbach 

Glad you solve the problem. I have found to my experience that this happens alot when some cells are too lowly expressed. Can you try again when filtering them.

**Comment by Li-ZhiD** [comment]
same error when testing stereo-seq chip with 10K spots * 5K genes.

```
  0%|                                                                                            | 0/800 [00:00<?, ?it/s]/mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/primitives.py:478: UserWarning: encoder.norm_topic.0.weight was not registered in the param store because requires_grad=False. You can silence this warning by calling my_module.train(False)
  warnings.warn(
Epoch Loss:481.458:   5%|██▉                                                            | 37/800 [02:04<42:56,  3.38s/it]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:191, in TraceHandler.__call__(self, *args, **kwargs)
    190 try:
--> 191     ret = self.fn(*args, **kwargs)
    192 except (ValueError, RuntimeError) as e:

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py:32, in _context_wrap(context, fn, *args, **kwargs)
     31 with context:
---> 32     return fn(*args, **kwargs)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/sctm/model.py:582, in spatialLDAModel.guide(self, x, sgc_x, categorical_covariate_code, time_covariate_code, not_cov, sample_idx, mask)
    580 kl_weight = 1
--> 582 pyro.sample("caux", dist.LogNormal(self.caux_loc, self.caux_scale))
    584 with poutine.mask(mask=mask):

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py:26, in DistributionMeta.__call__(cls, *args, **kwargs)
     25         return result
---> 26 return super().__call__(*args, **kwargs)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/torch.py:207, in LogNormal.__init__(self, loc, scale, validate_args)
    206 def __init__(self, loc, scale, validate_args=None):
--> 207     base_dist = Normal(loc, scale)
    208     # This differs from torch.distributions.LogNormal only in that base_dist is
    209     # a pyro.distributions.Normal rather than a torch.distributions.Normal.

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py:26, in DistributionMeta.__call__(cls, *args, **kwargs)
     25         return result
---> 26 return super().__call__(*args, **kwargs)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/torch/distributions/normal.py:57, in Normal.__init__(self, loc, scale, validate_args)
     56     batch_shape = self.loc.size()
---> 57 super().__init__(batch_shape, validate_args=validate_args)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/torch/distributions/distribution.py:70, in Distribution.__init__(self, batch_shape, event_shape, validate_args)
     69         if not valid.all():
---> 70             raise ValueError(
     71                 f"Expected parameter {param} "
     72                 f"({type(value).__name__} of shape {tuple(value.shape)}) "
     73                 f"of distribution {repr(self)} "
     74                 f"to satisfy the constraint {repr(constraint)}, "
     75                 f"but found invalid values:\n{value}"
     76             )
     77 super().__init__()

ValueError: Expected parameter loc (Parameter of shape (1,)) of distribution Normal(loc: Parameter containing:
tensor([nan], device='cuda:0', requires_grad=True), scale: tensor([nan], device='cuda:0', grad_fn=<AddBackward0>)) to satisfy the constraint Real(), but found invalid values:
Parameter containing:
tensor([nan], device='cuda:0', requires_grad=True)

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Cell In[33], line 2
      1 # We used a weighted sampler here as that the first timepoint is extremly small compared to the last timepoint.
----> 2 model.train(device="cuda:0", sampler = "R")

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/sctm/stamp.py:380, in STAMP.train(self, max_epochs, min_epochs, learning_rate, betas, not_cov_epochs, device, batch_size, sampler, weight_decay, iterations_to_anneal, min_kl, max_kl, early_stop, patience, shuffle, num_particles)
    378 # optimizer.zero_grad()
    379 for _, batch in enumerate(self.dataloader):
--> 380     batch_loss = svi.step(
    381         batch["x"].to(device),
    382         batch["sgc_x"].to(device),
    383         batch["categorical_covariate_codes"].to(device),
    384         (
    385             batch["time_covariate_codes"].to(device)
    386             if self.n_time >= 2
    387             else None
    388         ),
    389         not_cov,
    390         batch["sample_idx"],
    391         True,
    392     )
    393     losses.append(float(batch_loss))
    394     # iteration += 1
    395     # print(f"Full time{end - start}

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/svi.py:145, in SVI.step(self, *args, **kwargs)
    143 # get loss and compute gradients
    144 with poutine.trace(param_only=True) as param_capture:
--> 145     loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
    147 params = set(
    148     site["value"].unconstrained() for site in param_capture.trace.nodes.values()
    149 )
    151 # actually perform gradient steps
    152 # torch.optim objects gets instantiated for any params that haven't been seen yet

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_elbo.py:140, in Trace_ELBO.loss_and_grads(self, model, guide, *args, **kwargs)
    138 loss = 0.0
    139 # grab a trace from the generator
--> 140 for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
    141     loss_particle, surrogate_loss_particle = self._differentiable_loss_particle(
    142         model_trace, guide_trace
    143     )
    144     loss += loss_particle / self.num_particles

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/elbo.py:237, in ELBO._get_traces(self, model, guide, args, kwargs)
    235 else:
    236     for i in range(self.num_particles):
--> 237         yield self._get_trace(model, guide, args, kwargs)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_mean_field_elbo.py:82, in TraceMeanField_ELBO._get_trace(self, model, guide, args, kwargs)
     81 def _get_trace(self, model, guide, args, kwargs):
---> 82     model_trace, guide_trace = super()._get_trace(model, guide, args, kwargs)
     83     if is_validation_enabled():
     84         _check_mean_field_requirement(model_trace, guide_trace)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_elbo.py:57, in Trace_ELBO._get_trace(self, model, guide, args, kwargs)
     52 def _get_trace(self, model, guide, args, kwargs):
     53     """
     54     Returns a single trace from the guide, and the model that is run
     55     against it.
     56     """
---> 57     model_trace, guide_trace = get_importance_trace(
     58         "flat", self.max_plate_nesting, model, guide, args, kwargs
     59     )
     60     if is_validation_enabled():
     61         check_if_enumerated(guide_trace)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/enum.py:60, in get_importance_trace(graph_type, max_plate_nesting, model, guide, args, kwargs, detach)
     58     model_trace, guide_trace = unwrapped_guide.get_traces()
     59 else:
---> 60     guide_trace = poutine.trace(guide, graph_type=graph_type).get_trace(
     61         *args, **kwargs
     62     )
     63     if detach:
     64         guide_trace.detach_()

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:216, in TraceHandler.get_trace(self, *args, **kwargs)
    208 def get_trace(self, *args, **kwargs) -> Trace:
    209     """
    210     :returns: data structure
    211     :rtype: pyro.poutine.Trace
   (...)
    214     Calls this poutine and returns its trace instead of the function's return value.
    215     """
--> 216     self(*args, **kwargs)
    217     return self.msngr.get_trace()

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:198, in TraceHandler.__call__(self, *args, **kwargs)
    196         exc = exc_type("{}\n{}".format(exc_value, shapes))
    197         exc = exc.with_traceback(traceback)
--> 198         raise exc from e
    199     self.msngr.trace.add_node(
    200         "_RETURN", name="_RETURN", type="return", value=ret
    201     )
    202 return ret

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:191, in TraceHandler.__call__(self, *args, **kwargs)
    187 self.msngr.trace.add_node(
    188     "_INPUT", name="_INPUT", type="args", args=args, kwargs=kwargs
    189 )
    190 try:
--> 191     ret = self.fn(*args, **kwargs)
    192 except (ValueError, RuntimeError) as e:
    193     exc_type, exc_value, traceback = sys.exc_info()

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py:32, in _context_wrap(context, fn, *args, **kwargs)
     25 def _context_wrap(
     26     context: "Messenger",
     27     fn: Callable,
     28     *args: Any,
     29     **kwargs: Any,
     30 ) -> Any:
     31     with context:
---> 32         return fn(*args, **kwargs)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/sctm/model.py:582, in spatialLDAModel.guide(self, x, sgc_x, categorical_covariate_code, time_covariate_code, not_cov, sample_idx, mask)
    578 sample_plate = self.get_plate("sample", self.n_obs, sample_idx)
    580 kl_weight = 1
--> 582 pyro.sample("caux", dist.LogNormal(self.caux_loc, self.caux_scale))
    584 with poutine.mask(mask=mask):
    585     with self.genes_plate:

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py:26, in DistributionMeta.__call__(cls, *args, **kwargs)
     24     if result is not None:
     25         return result
---> 26 return super().__call__(*args, **kwargs)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/torch.py:207, in LogNormal.__init__(self, loc, scale, validate_args)
    206 def __init__(self, loc, scale, validate_args=None):
--> 207     base_dist = Normal(loc, scale)
    208     # This differs from torch.distributions.LogNormal only in that base_dist is
    209     # a pyro.distributions.Normal rather than a torch.distributions.Normal.
    210     super(torch.distributions.LogNormal, self).__init__(
    211         base_dist,
    212         torch.distributions.transforms.ExpTransform(),
    213         validate_args=validate_args,
    214     )

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py:26, in DistributionMeta.__call__(cls, *args, **kwargs)
     24     if result is not None:
     25         return result
---> 26 return super().__call__(*args, **kwargs)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/torch/distributions/normal.py:57, in Normal.__init__(self, loc, scale, validate_args)
     55 else:
     56     batch_shape = self.loc.size()
---> 57 super().__init__(batch_shape, validate_args=validate_args)

File /mnt/data1/ aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/torch/distributions/distribution.py:70, in Distribution.__init__(self, batch_shape, event_shape, validate_args)
     68         valid = constraint.check(value)
     69         if not valid.all():
---> 70             raise ValueError(
     71                 f"Expected parameter {param} "
     72                 f"({type(value).__name__} of shape {tuple(value.shape)}) "
     73                 f"of distribution {repr(self)} "
     74                 f"to satisfy the constraint {repr(constraint)}, "
     75                 f"but found invalid values:\n{value}"
     76             )
     77 super().__init__()

ValueError: Expected parameter loc (Parameter of shape (1,)) of distribution Normal(loc: Parameter containing:
tensor([nan], device='cuda:0', requires_grad=True), scale: tensor([nan], device='cuda:0', grad_fn=<AddBackward0>)) to satisfy the constraint Real(), but found invalid values:
Parameter containing:
tensor([nan], device='cuda:0', requires_grad=True)
Trace Shapes:      
 Param Sites:      
Sample Sites:      
  sample dist     |
        value 256 |
```

**Comment by Li-ZhiD** [comment]
I filtered spots and genes with 
```
sc.pp.filter_cells(adata, min_genes=50)
sctm.pp.filter_genes(adata, 0.03, expression_cutoff_99q = 0)
```
still raise error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:191, in TraceHandler.__call__(self, *args, **kwargs)
    190 try:
--> 191     ret = self.fn(*args, **kwargs)
    192 except (ValueError, RuntimeError) as e:

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py:32, in _context_wrap(context, fn, *args, **kwargs)
     31 with context:
---> 32     return fn(*args, **kwargs)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py:32, in _context_wrap(context, fn, *args, **kwargs)
     31 with context:
---> 32     return fn(*args, **kwargs)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/sctm/model.py:557, in spatialLDAModel.model(self, x, sgc_x, categorical_covariate_code, time_covariate_code, not_cov, sample_idx, mask)
    554     mean, inv_disp = broadcast_all(ls * mean + 1e-15, inv_disp)
    555     pyro.sample(
    556         "obs",
--> 557         dist.GammaPoisson(inv_disp, inv_disp / mean).to_event(1),
    558         obs=x,
    559     )
    560     # pyro.sample(
    561     #     "obs",
    562     #     dist.NegativeBinomial(inv_disp, mean / (mean + inv_disp)).to_event(1),
    563     #     obs=x,
    564     # )
    565 else:

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py:26, in DistributionMeta.__call__(cls, *args, **kwargs)
     25         return result
---> 26 return super().__call__(*args, **kwargs)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/conjugate.py:256, in GammaPoisson.__init__(self, concentration, rate, validate_args)
    255 self._gamma._validate_args = validate_args
--> 256 super().__init__(self._gamma._batch_shape, validate_args=validate_args)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/torch/distributions/distribution.py:68, in Distribution.__init__(self, batch_shape, event_shape, validate_args)
     67         if not valid.all():
---> 68             raise ValueError(
     69                 f"Expected parameter {param} "
     70                 f"({type(value).__name__} of shape {tuple(value.shape)}) "
     71                 f"of distribution {repr(self)} "
     72                 f"to satisfy the constraint {repr(constraint)}, "
     73                 f"but found invalid values:\n{value}"
     74             )
     75 super().__init__()

ValueError: Expected parameter rate (Tensor of shape (256, 10106)) of distribution GammaPoisson() to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<DivBackward0>)

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Cell In[47], line 3
      1 # We used a weighted sampler here as that the first timepoint is extremly small compared to the last timepoint.
      2 # model.train(device="cuda:0", sampler = "W", learning_rate=0.01)
----> 3 model.train(sampler = "W")

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/sctm/stamp.py:380, in STAMP.train(self, max_epochs, min_epochs, learning_rate, betas, not_cov_epochs, device, batch_size, sampler, weight_decay, iterations_to_anneal, min_kl, max_kl, early_stop, patience, shuffle, num_particles)
    378 # optimizer.zero_grad()
    379 for _, batch in enumerate(self.dataloader):
--> 380     batch_loss = svi.step(
    381         batch["x"].to(device),
    382         batch["sgc_x"].to(device),
    383         batch["categorical_covariate_codes"].to(device),
    384         (
    385             batch["time_covariate_codes"].to(device)
    386             if self.n_time >= 2
    387             else None
    388         ),
    389         not_cov,
    390         batch["sample_idx"],
    391         True,
    392     )
    393     losses.append(float(batch_loss))
    394     # iteration += 1
    395     # print(f"Full time{end - start}

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/svi.py:145, in SVI.step(self, *args, **kwargs)
    143 # get loss and compute gradients
    144 with poutine.trace(param_only=True) as param_capture:
--> 145     loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
    147 params = set(
    148     site["value"].unconstrained() for site in param_capture.trace.nodes.values()
    149 )
    151 # actually perform gradient steps
    152 # torch.optim objects gets instantiated for any params that haven't been seen yet

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_elbo.py:140, in Trace_ELBO.loss_and_grads(self, model, guide, *args, **kwargs)
    138 loss = 0.0
    139 # grab a trace from the generator
--> 140 for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
    141     loss_particle, surrogate_loss_particle = self._differentiable_loss_particle(
    142         model_trace, guide_trace
    143     )
    144     loss += loss_particle / self.num_particles

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/elbo.py:237, in ELBO._get_traces(self, model, guide, args, kwargs)
    235 else:
    236     for i in range(self.num_particles):
--> 237         yield self._get_trace(model, guide, args, kwargs)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_mean_field_elbo.py:82, in TraceMeanField_ELBO._get_trace(self, model, guide, args, kwargs)
     81 def _get_trace(self, model, guide, args, kwargs):
---> 82     model_trace, guide_trace = super()._get_trace(model, guide, args, kwargs)
     83     if is_validation_enabled():
     84         _check_mean_field_requirement(model_trace, guide_trace)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_elbo.py:57, in Trace_ELBO._get_trace(self, model, guide, args, kwargs)
     52 def _get_trace(self, model, guide, args, kwargs):
     53     """
     54     Returns a single trace from the guide, and the model that is run
     55     against it.
     56     """
---> 57     model_trace, guide_trace = get_importance_trace(
     58         "flat", self.max_plate_nesting, model, guide, args, kwargs
     59     )
     60     if is_validation_enabled():
     61         check_if_enumerated(guide_trace)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/enum.py:65, in get_importance_trace(graph_type, max_plate_nesting, model, guide, args, kwargs, detach)
     63     if detach:
     64         guide_trace.detach_()
---> 65     model_trace = poutine.trace(
     66         poutine.replay(model, trace=guide_trace), graph_type=graph_type
     67     ).get_trace(*args, **kwargs)
     69 if is_validation_enabled():
     70     check_model_guide_match(model_trace, guide_trace, max_plate_nesting)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:216, in TraceHandler.get_trace(self, *args, **kwargs)
    208 def get_trace(self, *args, **kwargs) -> Trace:
    209     """
    210     :returns: data structure
    211     :rtype: pyro.poutine.Trace
   (...)
    214     Calls this poutine and returns its trace instead of the function's return value.
    215     """
--> 216     self(*args, **kwargs)
    217     return self.msngr.get_trace()

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:198, in TraceHandler.__call__(self, *args, **kwargs)
    196         exc = exc_type("{}\n{}".format(exc_value, shapes))
    197         exc = exc.with_traceback(traceback)
--> 198         raise exc from e
    199     self.msngr.trace.add_node(
    200         "_RETURN", name="_RETURN", type="return", value=ret
    201     )
    202 return ret

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:191, in TraceHandler.__call__(self, *args, **kwargs)
    187 self.msngr.trace.add_node(
    188     "_INPUT", name="_INPUT", type="args", args=args, kwargs=kwargs
    189 )
    190 try:
--> 191     ret = self.fn(*args, **kwargs)
    192 except (ValueError, RuntimeError) as e:
    193     exc_type, exc_value, traceback = sys.exc_info()

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py:32, in _context_wrap(context, fn, *args, **kwargs)
     25 def _context_wrap(
     26     context: "Messenger",
     27     fn: Callable,
     28     *args: Any,
     29     **kwargs: Any,
     30 ) -> Any:
     31     with context:
---> 32         return fn(*args, **kwargs)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py:32, in _context_wrap(context, fn, *args, **kwargs)
     25 def _context_wrap(
     26     context: "Messenger",
     27     fn: Callable,
     28     *args: Any,
     29     **kwargs: Any,
     30 ) -> Any:
     31     with context:
---> 32         return fn(*args, **kwargs)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/sctm/model.py:557, in spatialLDAModel.model(self, x, sgc_x, categorical_covariate_code, time_covariate_code, not_cov, sample_idx, mask)
    553     inv_disp = 1 / disp**2
    554     mean, inv_disp = broadcast_all(ls * mean + 1e-15, inv_disp)
    555     pyro.sample(
    556         "obs",
--> 557         dist.GammaPoisson(inv_disp, inv_disp / mean).to_event(1),
    558         obs=x,
    559     )
    560     # pyro.sample(
    561     #     "obs",
    562     #     dist.NegativeBinomial(inv_disp, mean / (mean + inv_disp)).to_event(1),
    563     #     obs=x,
    564     # )
    565 else:
    566     raise ValueError("Gene distribution not supported")

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py:26, in DistributionMeta.__call__(cls, *args, **kwargs)
     24     if result is not None:
     25         return result
---> 26 return super().__call__(*args, **kwargs)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/conjugate.py:256, in GammaPoisson.__init__(self, concentration, rate, validate_args)
    254 self._gamma = Gamma(concentration, rate, validate_args=False)
    255 self._gamma._validate_args = validate_args
--> 256 super().__init__(self._gamma._batch_shape, validate_args=validate_args)

File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/torch/distributions/distribution.py:68, in Distribution.__init__(self, batch_shape, event_shape, validate_args)
     66         valid = constraint.check(value)
     67         if not valid.all():
---> 68             raise ValueError(
     69                 f"Expected parameter {param} "
     70                 f"({type(value).__name__} of shape {tuple(value.shape)}) "
     71                 f"of distribution {repr(self)} "
     72                 f"to satisfy the constraint {repr(constraint)}, "
     73                 f"but found invalid values:\n{value}"
     74             )
     75 super().__init__()

ValueError: Expected parameter rate (Tensor of shape (256, 10106)) of distribution GammaPoisson() to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<DivBackward0>)
                           Trace Shapes:                  
                            Param Sites:                  
          stamp$$$caux_loc_unconstrained              1   
        stamp$$$caux_scale_unconstrained              1   
    stamp$$$z_topic_lr_loc_unconstrained       50    50   
  stamp$$$z_topic_lr_scale_unconstrained       50    50   
  stamp$$$z_topic_diag_loc_unconstrained              1   
stamp$$$z_topic_diag_scale_unconstrained              1   
         stamp$$$delta_loc_unconstrained          10106   
       stamp$$$delta_scale_unconstrained          10106   
            stamp$$$bg_loc_unconstrained          10106   
          stamp$$$bg_scale_unconstrained          10106   
           stamp$$$tau_loc_unconstrained       50     1   
         stamp$$$tau_scale_unconstrained       50     1   
        stamp$$$lambda_loc_unconstrained       50 10106   
      stamp$$$lambda_scale_unconstrained       50 10106   
     stamp$$$batch_tau_loc_unconstrained       50     1   
   stamp$$$batch_tau_scale_unconstrained       50     1   
   stamp$$$batch_delta_loc_unconstrained       26 10106   
 stamp$$$batch_delta_scale_unconstrained       26 10106   
          stamp$$$beta_loc_unconstrained       50 10106   
        stamp$$$beta_scale_unconstrained       50 10106   
          stamp$$$disp_loc_unconstrained          10106   
        stamp$$$disp_scale_unconstrained          10106   
           stamp$$$encoder.base.1.weight      128 20212   
             stamp$$$encoder.base.1.bias            128   
           stamp$$$encoder.base.2.weight            128   
             stamp$$$encoder.base.2.bias            128   
         stamp$$$encoder.mu_topic.weight       50   128   
           stamp$$$encoder.mu_topic.bias             50   
       stamp$$$encoder.norm_topic.0.bias             50   
       stamp$$$encoder.norm_topic.1.bias             50   
       stamp$$$encoder.norm_topic.2.bias             50   
       stamp$$$encoder.norm_topic.3.bias             50   
       stamp$$$encoder.norm_topic.4.bias             50   
       stamp$$$encoder.norm_topic.5.bias             50   
       stamp$$$encoder.norm_topic.6.bias             50   
       stamp$$$encoder.norm_topic.7.bias             50   
       stamp$$$encoder.norm_topic.8.bias             50   
       stamp$$$encoder.norm_topic.9.bias             50   
      stamp$$$encoder.norm_topic.10.bias             50   
      stamp$$$encoder.norm_topic.11.bias             50   
      stamp$$$encoder.norm_topic.12.bias             50   
      stamp$$$encoder.norm_topic.13.bias             50   
      stamp$$$encoder.norm_topic.14.bias             50   
      stamp$$$encoder.norm_topic.15.bias             50   
      stamp$$$encoder.norm_topic.16.bias             50   
      stamp$$$encoder.norm_topic.17.bias             50   
      stamp$$$encoder.norm_topic.18.bias             50   
      stamp$$$encoder.norm_topic.19.bias             50   
      stamp$$$encoder.norm_topic.20.bias             50   
      stamp$$$encoder.norm_topic.21.bias             50   
      stamp$$$encoder.norm_topic.22.bias             50   
      stamp$$$encoder.norm_topic.23.bias             50   
      stamp$$$encoder.norm_topic.24.bias             50   
      stamp$$$encoder.norm_topic.25.bias             50   
       stamp$$$encoder.diag_topic.weight       50   128   
         stamp$$$encoder.diag_topic.bias             50   
                           Sample Sites:                  
                             sample dist              |   
                                   value      256     |   
                               caux dist        1     |   
                                   value        1     |   
                              delta dist    10106     |   
                                   value    10106     |   
                                 bg dist    10106     |   
                                   value    10106     |   
                                tau dist 50     1     |   
                                   value 50     1     |   
                            lambda_ dist 50 10106     |   
                                   value 50 10106     |   
                          batch_tau dist 50     1     |   
                                   value 50     1     |   
                        batch_delta dist 26 10106     |   
                                   value 26 10106     |   
                               beta dist 50 10106     |   
                                   value 50 10106     |   
                       z_topic_diag dist        1     |   
                                   value        1     |   
                         z_topic_lr dist 50    50     |   
                                   value 50    50     |   
                               disp dist    10106     |   
                                   value    10106     |   
                            z_topic dist      256     | 50
                                   value      256     | 50
```
how can we know if the filtering is suitable?

**Comment by Chengwei94** [comment]
@Li-ZhiD, I think this filtering should be fine. Is your dataset public? If yes, I can download and try it out as I have not tested it on Xenium before. Can you check the minimum number of cells and genes per cell? Usually theres a problem if its too low

**Comment by Li-ZhiD** [comment]
I merged several stereo-seq chips using scanpy.concat, and then filtered spots and genes by
```
sc.pp.filter_cells(adata, min_genes=50)
sctm.pp.filter_genes(adata, 0.05, expression_cutoff_99q = 0)
```
There are 7K genes remaining. Is the gene count acceptable?

<img width="487" alt="image" src="https://github.com/user-attachments/assets/04324929-122a-4b92-93a0-85a73b5b68fa">

**Comment by Li-ZhiD** [comment]
@Chengwei94 I am interested in this tool and want to use this tool in my project as soon as possible. What can I do to find out?

**Comment by Chengwei94** [comment]
@Li-ZhiD I think what you can try is filter for each sample separately then concat them. Right now, what you are doing may result in low number of counts in one sample, therefore leading to these nuemrical errors. I will add some function for that in the future. 

Are you doing time-series? I think the time-series might have some problem with numerical stability with 0.01 learning rate and I would recommend 0.001 for time-series if you are doing ts

**Comment by Li-ZhiD** [comment]
Thank you! Not a time-series, but several chips from one sample. I went through this tool for one chip after filtering. 
Some chips only have a subset of cell types (Maybe this causes that error). There are remaining NAs or 0 if I filter each chip separately and then concat them.

**Comment by Chengwei94** [comment]
Are you running with these code?

model = sctm.stamp.STAMP(
    adata,
    n_topics = n_topics,
    layer="counts",
    gene_likelihood="nb")

model.train(learning_rate = 0.01)

**Comment by Li-ZhiD** [comment]
I tried the code below with several parameter alternatives:
coord_type: default or "grid" in spatial_neighbors
sampler: "W" or "R" in model.train

```
# We uses roughly (1/1000) * size
sq.gr.spatial_neighbors(
    adata,
    spatial_key='spatial',
    library_key='Chip_name',
    coord_type='grid',
    n_neighs = 8,
    # n_neighs=round(1 / 1000 * adata.n_obs)
)

sctm.seed.seed_everything(0)

model = sctm.stamp.STAMP(
    adata,
    # adata[:, adata.var.highly_variable],
    n_topics=50,
    layer="counts",
    categorical_covariate_keys=['Chip_name'],
    # time_covariate_keys="time",
    # gene_likelihood="poison",
)

model.train(sampler = "W")
```

**Comment by Chengwei94** [comment]
I think the problem is still the filtering here. Since we you multiple batches, but when you filter you filter at once, so there might be a batch/chip where there are no gene expressed. Therefore, I think you need to filter each before concat. But if its the same sample, you can remove actually just remove the categorical_covariate_keys=['Chip_name'] if theres not much batch effects

**Comment by Li-ZhiD** [comment]
Thank you! I will try both methods you mentioned. I hope updates to address these batch situations will be released soon.

**Comment by Li-ZhiD** [comment]
Sadly, the output topics are affected by the batches after removing the categorical_covariate_keys=['Chip_name'].

**Comment by Li-ZhiD** [comment]
Filter each sample separately, and then concatenate them. This approach works for a subset of chips. I will apply it for all.
Thank you!

**Comment by Li-ZhiD** [comment]
> Filter each sample separately, and then concatenate them. This approach works for a subset of chips. I will apply it for all. Thank you!

For all chips, the same error was raised as above.

**Comment by Chengwei94** [comment]
I think for now you can just lower the learning rate till we find the problem

**Comment by Li-ZhiD** [comment]
> I think for now you can just lower the learning rate till we find the problem

It didn't work for 0.001 and 0.0001.

**Comment by Li-ZhiD** [comment]
Methods in your paper mentioned, "We next selected 6,000 highly variable genes, to which we then applied another filtering of spatially variable genes with Moran’s I down to 2,000 genes."

How to select spatially variable genes by using squidy for multiple chips?
I tried:
1, calculate highly variable genes for each chip separately
2, call spatially variable genes of highly variable genes for each chip separately using squidy
3, merge top 3K spatially variable genes of all chips
4, concat adata and call highly variable genes with "batch='Chip_name'"
5, intersect merged top spatially variable genes from 3 and highly variable genes from 4 as final variable gene sets

Is that OK?

**Comment by Chengwei94** [comment]
Can you share eveyryth you run and the full error

**Comment by Li-ZhiD** [comment]
Do not calculate spatially variable genes, code below:

```
adata = adata[:, adata.var.index.isin(cd_gene)] ## keep coding gene

adata_lst = []

for i in tqdm([
    "chip_1", "chip_1", "chip_1", "chip_1", "chip_1", "chip_1", "chip_1", "chip_1", "chip_1"
]):
    adata_i = adata[adata.obs['Chip_name'].isin([i])]
    sc.pp.filter_cells(adata_i, min_genes=50)
    sctm.pp.filter_genes(adata_i, 0.01, expression_cutoff_99q = 0)
    
    adata_lst.append(adata_i)

adata = sc.concat(adata_lst, join="outer")

adata.layers["counts"] = adata.X.copy()
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

sc.pp.highly_variable_genes(
    adata,
    layer='counts',
    n_top_genes=6000,
    min_mean=0.0125,
    max_mean=3,
    min_disp=0.5,
    flavor='seurat_v3',
    batch_key='Chip_name'
)

# We uses roughly (1/1000) * size
sq.gr.spatial_neighbors(
    adata,
    spatial_key='spatial',
    library_key='Chip_name',
    coord_type='grid',
    n_neighs = 8,
    # n_neighs=round(1 / 1000 * adata.n_obs)
)

sctm.seed.seed_everything(0)

model = sctm.stamp.STAMP(
    # adata,
    adata[:, adata.var.highly_variable],
    n_topics=30,
    layer="counts",
    categorical_covariate_keys=['Chip_name'],
    # time_covariate_keys="time",
    # gene_likelihood="poison",
)

model.train()
```

errors raised after about 3 Epoch:

> I filtered spots and genes with
> 
> ```
> sc.pp.filter_cells(adata, min_genes=50)
> sctm.pp.filter_genes(adata, 0.03, expression_cutoff_99q = 0)
> ```
> 
> still raise error
> 
> ```
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:191, in TraceHandler.__call__(self, *args, **kwargs)
>     190 try:
> --> 191     ret = self.fn(*args, **kwargs)
>     192 except (ValueError, RuntimeError) as e:
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py:32, in _context_wrap(context, fn, *args, **kwargs)
>      31 with context:
> ---> 32     return fn(*args, **kwargs)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py:32, in _context_wrap(context, fn, *args, **kwargs)
>      31 with context:
> ---> 32     return fn(*args, **kwargs)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/sctm/model.py:557, in spatialLDAModel.model(self, x, sgc_x, categorical_covariate_code, time_covariate_code, not_cov, sample_idx, mask)
>     554     mean, inv_disp = broadcast_all(ls * mean + 1e-15, inv_disp)
>     555     pyro.sample(
>     556         "obs",
> --> 557         dist.GammaPoisson(inv_disp, inv_disp / mean).to_event(1),
>     558         obs=x,
>     559     )
>     560     # pyro.sample(
>     561     #     "obs",
>     562     #     dist.NegativeBinomial(inv_disp, mean / (mean + inv_disp)).to_event(1),
>     563     #     obs=x,
>     564     # )
>     565 else:
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py:26, in DistributionMeta.__call__(cls, *args, **kwargs)
>      25         return result
> ---> 26 return super().__call__(*args, **kwargs)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/conjugate.py:256, in GammaPoisson.__init__(self, concentration, rate, validate_args)
>     255 self._gamma._validate_args = validate_args
> --> 256 super().__init__(self._gamma._batch_shape, validate_args=validate_args)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/torch/distributions/distribution.py:68, in Distribution.__init__(self, batch_shape, event_shape, validate_args)
>      67         if not valid.all():
> ---> 68             raise ValueError(
>      69                 f"Expected parameter {param} "
>      70                 f"({type(value).__name__} of shape {tuple(value.shape)}) "
>      71                 f"of distribution {repr(self)} "
>      72                 f"to satisfy the constraint {repr(constraint)}, "
>      73                 f"but found invalid values:\n{value}"
>      74             )
>      75 super().__init__()
> 
> ValueError: Expected parameter rate (Tensor of shape (256, 10106)) of distribution GammaPoisson() to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
> tensor([[nan, nan, nan,  ..., nan, nan, nan],
>         [nan, nan, nan,  ..., nan, nan, nan],
>         [nan, nan, nan,  ..., nan, nan, nan],
>         ...,
>         [nan, nan, nan,  ..., nan, nan, nan],
>         [nan, nan, nan,  ..., nan, nan, nan],
>         [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
>        grad_fn=<DivBackward0>)
> 
> The above exception was the direct cause of the following exception:
> 
> ValueError                                Traceback (most recent call last)
> Cell In[47], line 3
>       1 # We used a weighted sampler here as that the first timepoint is extremly small compared to the last timepoint.
>       2 # model.train(device="cuda:0", sampler = "W", learning_rate=0.01)
> ----> 3 model.train(sampler = "W")
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/sctm/stamp.py:380, in STAMP.train(self, max_epochs, min_epochs, learning_rate, betas, not_cov_epochs, device, batch_size, sampler, weight_decay, iterations_to_anneal, min_kl, max_kl, early_stop, patience, shuffle, num_particles)
>     378 # optimizer.zero_grad()
>     379 for _, batch in enumerate(self.dataloader):
> --> 380     batch_loss = svi.step(
>     381         batch["x"].to(device),
>     382         batch["sgc_x"].to(device),
>     383         batch["categorical_covariate_codes"].to(device),
>     384         (
>     385             batch["time_covariate_codes"].to(device)
>     386             if self.n_time >= 2
>     387             else None
>     388         ),
>     389         not_cov,
>     390         batch["sample_idx"],
>     391         True,
>     392     )
>     393     losses.append(float(batch_loss))
>     394     # iteration += 1
>     395     # print(f"Full time{end - start}
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/svi.py:145, in SVI.step(self, *args, **kwargs)
>     143 # get loss and compute gradients
>     144 with poutine.trace(param_only=True) as param_capture:
> --> 145     loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
>     147 params = set(
>     148     site["value"].unconstrained() for site in param_capture.trace.nodes.values()
>     149 )
>     151 # actually perform gradient steps
>     152 # torch.optim objects gets instantiated for any params that haven't been seen yet
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_elbo.py:140, in Trace_ELBO.loss_and_grads(self, model, guide, *args, **kwargs)
>     138 loss = 0.0
>     139 # grab a trace from the generator
> --> 140 for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
>     141     loss_particle, surrogate_loss_particle = self._differentiable_loss_particle(
>     142         model_trace, guide_trace
>     143     )
>     144     loss += loss_particle / self.num_particles
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/elbo.py:237, in ELBO._get_traces(self, model, guide, args, kwargs)
>     235 else:
>     236     for i in range(self.num_particles):
> --> 237         yield self._get_trace(model, guide, args, kwargs)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_mean_field_elbo.py:82, in TraceMeanField_ELBO._get_trace(self, model, guide, args, kwargs)
>      81 def _get_trace(self, model, guide, args, kwargs):
> ---> 82     model_trace, guide_trace = super()._get_trace(model, guide, args, kwargs)
>      83     if is_validation_enabled():
>      84         _check_mean_field_requirement(model_trace, guide_trace)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/trace_elbo.py:57, in Trace_ELBO._get_trace(self, model, guide, args, kwargs)
>      52 def _get_trace(self, model, guide, args, kwargs):
>      53     """
>      54     Returns a single trace from the guide, and the model that is run
>      55     against it.
>      56     """
> ---> 57     model_trace, guide_trace = get_importance_trace(
>      58         "flat", self.max_plate_nesting, model, guide, args, kwargs
>      59     )
>      60     if is_validation_enabled():
>      61         check_if_enumerated(guide_trace)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/infer/enum.py:65, in get_importance_trace(graph_type, max_plate_nesting, model, guide, args, kwargs, detach)
>      63     if detach:
>      64         guide_trace.detach_()
> ---> 65     model_trace = poutine.trace(
>      66         poutine.replay(model, trace=guide_trace), graph_type=graph_type
>      67     ).get_trace(*args, **kwargs)
>      69 if is_validation_enabled():
>      70     check_model_guide_match(model_trace, guide_trace, max_plate_nesting)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:216, in TraceHandler.get_trace(self, *args, **kwargs)
>     208 def get_trace(self, *args, **kwargs) -> Trace:
>     209     """
>     210     :returns: data structure
>     211     :rtype: pyro.poutine.Trace
>    (...)
>     214     Calls this poutine and returns its trace instead of the function's return value.
>     215     """
> --> 216     self(*args, **kwargs)
>     217     return self.msngr.get_trace()
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:198, in TraceHandler.__call__(self, *args, **kwargs)
>     196         exc = exc_type("{}\n{}".format(exc_value, shapes))
>     197         exc = exc.with_traceback(traceback)
> --> 198         raise exc from e
>     199     self.msngr.trace.add_node(
>     200         "_RETURN", name="_RETURN", type="return", value=ret
>     201     )
>     202 return ret
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py:191, in TraceHandler.__call__(self, *args, **kwargs)
>     187 self.msngr.trace.add_node(
>     188     "_INPUT", name="_INPUT", type="args", args=args, kwargs=kwargs
>     189 )
>     190 try:
> --> 191     ret = self.fn(*args, **kwargs)
>     192 except (ValueError, RuntimeError) as e:
>     193     exc_type, exc_value, traceback = sys.exc_info()
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py:32, in _context_wrap(context, fn, *args, **kwargs)
>      25 def _context_wrap(
>      26     context: "Messenger",
>      27     fn: Callable,
>      28     *args: Any,
>      29     **kwargs: Any,
>      30 ) -> Any:
>      31     with context:
> ---> 32         return fn(*args, **kwargs)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/poutine/messenger.py:32, in _context_wrap(context, fn, *args, **kwargs)
>      25 def _context_wrap(
>      26     context: "Messenger",
>      27     fn: Callable,
>      28     *args: Any,
>      29     **kwargs: Any,
>      30 ) -> Any:
>      31     with context:
> ---> 32         return fn(*args, **kwargs)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/sctm/model.py:557, in spatialLDAModel.model(self, x, sgc_x, categorical_covariate_code, time_covariate_code, not_cov, sample_idx, mask)
>     553     inv_disp = 1 / disp**2
>     554     mean, inv_disp = broadcast_all(ls * mean + 1e-15, inv_disp)
>     555     pyro.sample(
>     556         "obs",
> --> 557         dist.GammaPoisson(inv_disp, inv_disp / mean).to_event(1),
>     558         obs=x,
>     559     )
>     560     # pyro.sample(
>     561     #     "obs",
>     562     #     dist.NegativeBinomial(inv_disp, mean / (mean + inv_disp)).to_event(1),
>     563     #     obs=x,
>     564     # )
>     565 else:
>     566     raise ValueError("Gene distribution not supported")
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/distribution.py:26, in DistributionMeta.__call__(cls, *args, **kwargs)
>      24     if result is not None:
>      25         return result
> ---> 26 return super().__call__(*args, **kwargs)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/pyro/distributions/conjugate.py:256, in GammaPoisson.__init__(self, concentration, rate, validate_args)
>     254 self._gamma = Gamma(concentration, rate, validate_args=False)
>     255 self._gamma._validate_args = validate_args
> --> 256 super().__init__(self._gamma._batch_shape, validate_args=validate_args)
> 
> File /mnt/data1/aaa/software/miniconda3/envs/sctm/lib/python3.8/site-packages/torch/distributions/distribution.py:68, in Distribution.__init__(self, batch_shape, event_shape, validate_args)
>      66         valid = constraint.check(value)
>      67         if not valid.all():
> ---> 68             raise ValueError(
>      69                 f"Expected parameter {param} "
>      70                 f"({type(value).__name__} of shape {tuple(value.shape)}) "
>      71                 f"of distribution {repr(self)} "
>      72                 f"to satisfy the constraint {repr(constraint)}, "
>      73                 f"but found invalid values:\n{value}"
>      74             )
>      75 super().__init__()
> 
> ValueError: Expected parameter rate (Tensor of shape (256, 10106)) of distribution GammaPoisson() to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
> tensor([[nan, nan, nan,  ..., nan, nan, nan],
>         [nan, nan, nan,  ..., nan, nan, nan],
>         [nan, nan, nan,  ..., nan, nan, nan],
>         ...,
>         [nan, nan, nan,  ..., nan, nan, nan],
>         [nan, nan, nan,  ..., nan, nan, nan],
>         [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
>        grad_fn=<DivBackward0>)
>                            Trace Shapes:                  
>                             Param Sites:                  
>           stamp$$$caux_loc_unconstrained              1   
>         stamp$$$caux_scale_unconstrained              1   
>     stamp$$$z_topic_lr_loc_unconstrained       50    50   
>   stamp$$$z_topic_lr_scale_unconstrained       50    50   
>   stamp$$$z_topic_diag_loc_unconstrained              1   
> stamp$$$z_topic_diag_scale_unconstrained              1   
>          stamp$$$delta_loc_unconstrained          10106   
>        stamp$$$delta_scale_unconstrained          10106   
>             stamp$$$bg_loc_unconstrained          10106   
>           stamp$$$bg_scale_unconstrained          10106   
>            stamp$$$tau_loc_unconstrained       50     1   
>          stamp$$$tau_scale_unconstrained       50     1   
>         stamp$$$lambda_loc_unconstrained       50 10106   
>       stamp$$$lambda_scale_unconstrained       50 10106   
>      stamp$$$batch_tau_loc_unconstrained       50     1   
>    stamp$$$batch_tau_scale_unconstrained       50     1   
>    stamp$$$batch_delta_loc_unconstrained       26 10106   
>  stamp$$$batch_delta_scale_unconstrained       26 10106   
>           stamp$$$beta_loc_unconstrained       50 10106   
>         stamp$$$beta_scale_unconstrained       50 10106   
>           stamp$$$disp_loc_unconstrained          10106   
>         stamp$$$disp_scale_unconstrained          10106   
>            stamp$$$encoder.base.1.weight      128 20212   
>              stamp$$$encoder.base.1.bias            128   
>            stamp$$$encoder.base.2.weight            128   
>              stamp$$$encoder.base.2.bias            128   
>          stamp$$$encoder.mu_topic.weight       50   128   
>            stamp$$$encoder.mu_topic.bias             50   
>        stamp$$$encoder.norm_topic.0.bias             50   
>        stamp$$$encoder.norm_topic.1.bias             50   
>        stamp$$$encoder.norm_topic.2.bias             50   
>        stamp$$$encoder.norm_topic.3.bias             50   
>        stamp$$$encoder.norm_topic.4.bias             50   
>        stamp$$$encoder.norm_topic.5.bias             50   
>        stamp$$$encoder.norm_topic.6.bias             50   
>        stamp$$$encoder.norm_topic.7.bias             50   
>        stamp$$$encoder.norm_topic.8.bias             50   
>        stamp$$$encoder.norm_topic.9.bias             50   
>       stamp$$$encoder.norm_topic.10.bias             50   
>       stamp$$$encoder.norm_topic.11.bias             50   
>       stamp$$$encoder.norm_topic.12.bias             50   
>       stamp$$$encoder.norm_topic.13.bias             50   
>       stamp$$$encoder.norm_topic.14.bias             50   
>       stamp$$$encoder.norm_topic.15.bias             50   
>       stamp$$$encoder.norm_topic.16.bias             50   
>       stamp$$$encoder.norm_topic.17.bias             50   
>       stamp$$$encoder.norm_topic.18.bias             50   
>       stamp$$$encoder.norm_topic.19.bias             50   
>       stamp$$$encoder.norm_topic.20.bias             50   
>       stamp$$$encoder.norm_topic.21.bias             50   
>       stamp$$$encoder.norm_topic.22.bias             50   
>       stamp$$$encoder.norm_topic.23.bias             50   
>       stamp$$$encoder.norm_topic.24.bias             50   
>       stamp$$$encoder.norm_topic.25.bias             50   
>        stamp$$$encoder.diag_topic.weight       50   128   
>          stamp$$$encoder.diag_topic.bias             50   
>                            Sample Sites:                  
>                              sample dist              |   
>                                    value      256     |   
>                                caux dist        1     |   
>                                    value        1     |   
>                               delta dist    10106     |   
>                                    value    10106     |   
>                                  bg dist    10106     |   
>                                    value    10106     |   
>                                 tau dist 50     1     |   
>                                    value 50     1     |   
>                             lambda_ dist 50 10106     |   
>                                    value 50 10106     |   
>                           batch_tau dist 50     1     |   
>                                    value 50     1     |   
>                         batch_delta dist 26 10106     |   
>                                    value 26 10106     |   
>                                beta dist 50 10106     |   
>                                    value 50 10106     |   
>                        z_topic_diag dist        1     |   
>                                    value        1     |   
>                          z_topic_lr dist 50    50     |   
>                                    value 50    50     |   
>                                disp dist    10106     |   
>                                    value    10106     |   
>                             z_topic dist      256     | 50
>                                    value      256     | 50
> ```
> 
> how can we know if the filtering is suitable?

**Comment by Chengwei94** [comment]
A problem i saw here is the outer join, can you try with inner join when u concat

**Comment by Li-ZhiD** [comment]
Thank you!
Of our data, cell type changes from the first to the last chip. The last chip has specific cell types. So, inner join may cause cell type-specific gene information lost. (I will try inner join later)
I tested the first 5 chips by using outer join, and the result looked good, but it failed for all chips. Maybe the chip-specific genes/topics cause running problems.

**Comment by Chengwei94** [comment]
Oh, yea thats a legit concern. I will try to solve this problem on my side as well, and update here when we update sctm to the next ver

**Comment by Li-ZhiD** [comment]
Thank you very much!

**Comment by Li-ZhiD** [comment]
@Chengwei94 any progress on this issue? Thank you!
